### ISSUE TITLE
Copy level download URLs for entire ward

### ISSUE THREAD

**Issue by huantianad** [NoahTheNerd/unpaid-overtime#2]
If you paste new line separated links in the CLS URL importer, it'll install all of them, thus reducing the amount of imports you have to do.

**Comment by ixnoahlive** [comment]
Issue resolved as of [e91cfa8](https://github.com/NoahTheNerd/unpaid-overtime/commit/e91cfa80b91c6abdba2f9bfdf3a76a2e0e10ac7b)
